version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpass}
      POSTGRES_DB: ${POSTGRES_DB:-agilepm}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ../AgilePM-API
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ../AgilePM-UI
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
